// <auto-generated />
using System;
using Aethernet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethernet.Data.Migrations
{
    [DbContext(typeof(AethernetDbContext))]
    [Migration("20260608012734_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethernet.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("TargetGid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetUid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUid");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.BannedUserEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.BlockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OtherUid");

                    b.HasIndex("OwnerUid", "OtherUid")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.FileCacheEntity", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FirstUploaderUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ForbiddenReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsForbidden")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Hash");

                    b.HasIndex("FirstUploaderUid");

                    b.HasIndex("OrphanedAt");

                    b.ToTable("FileCache");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupBanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("UidBanned")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UidBannedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Gid", "UidBanned")
                        .IsUnique();

                    b.ToTable("GroupBans");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupEntity", b =>
                {
                    b.Property<string>("Gid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Alias")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultUserPermissions")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MemberLimit")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Gid");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("OwnerUid");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupPairEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("UserPermissions")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.HasIndex("Gid", "Uid")
                        .IsUnique();

                    b.ToTable("GroupPairs");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.PairEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("OwnPermissions")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OtherUid");

                    b.HasIndex("OwnerUid", "OtherUid")
                        .IsUnique();

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.ProfileReportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportedUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReporterUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUid");

                    b.HasIndex("Resolved");

                    b.ToTable("ProfileReports");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Uid");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Alias")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("FileQuotaBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileDescription")
                        .HasColumnType("text");

                    b.Property<bool>("ProfileIsFlagged")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfileIsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureBase64")
                        .HasColumnType("text");

                    b.Property<string>("RecoverySecretHash")
                        .HasColumnType("text");

                    b.Property<string>("SecretKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupBanEntity", b =>
                {
                    b.HasOne("Aethernet.Data.Entities.GroupEntity", "Group")
                        .WithMany("Bans")
                        .HasForeignKey("Gid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupEntity", b =>
                {
                    b.HasOne("Aethernet.Data.Entities.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupPairEntity", b =>
                {
                    b.HasOne("Aethernet.Data.Entities.GroupEntity", "Group")
                        .WithMany("Members")
                        .HasForeignKey("Gid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethernet.Data.Entities.UserEntity", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.PairEntity", b =>
                {
                    b.HasOne("Aethernet.Data.Entities.UserEntity", "Other")
                        .WithMany("ReceivedPairs")
                        .HasForeignKey("OtherUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethernet.Data.Entities.UserEntity", "Owner")
                        .WithMany("InitiatedPairs")
                        .HasForeignKey("OwnerUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Other");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.GroupEntity", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Aethernet.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("InitiatedPairs");

                    b.Navigation("ReceivedPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
